# Generated by Django 3.0.2 on 2020-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
