# Generated by Django 3.0.2 on 2020-02-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_slide_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide'},
        ),
    ]
