# Generated by Django 3.0.2 on 2020-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_auto_20200227_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='notes',
            field=models.CharField(default='None', max_length=2000),
        ),
    ]
