# Generated by Django 3.0.2 on 2020-02-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_slide_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='title',
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.CharField(help_text='The HTML content of your slide.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='slide',
            name='display',
            field=models.BooleanField(default=True, help_text='If unchecked the slide will not be displayed.'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='name',
            field=models.CharField(help_text='A unique ID for your slide.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='notes',
            field=models.CharField(default='None', help_text='The hiddens notes for the slide.', max_length=2000),
        ),
    ]
