# Generated by Django 3.0.2 on 2020-02-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_auto_20200229_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(help_text='The HTML content of your slide.'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='notes',
            field=models.TextField(help_text='The hiddens notes for the slide.'),
        ),
    ]
