# Generated by Django 3.0.2 on 2020-02-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_auto_20200229_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='notes',
            field=models.TextField(default='None', help_text='The hiddens notes for the slide.'),
        ),
    ]
